version: "3.9"
services:
  mysql-db:
    image: mysql:latest
    container_name: shooting-miner-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ShootingMinerDB
      MYSQL_USER: api_server
      MYSQL_PASSWORD: api_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
