version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql_data:/var/lib/mysql

  http-server:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-test
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/myapp
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: devpass
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - mysql-db

volumes:
  mysql_data:
