# 1) JDK 베이스 이미지 선택 (프로젝트 JDK 버전에 맞춰 변경)
FROM alpine/java:17

# 2) jar 파일을 컨테이너 안으로 복사
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

# 3) 애플리케이션 포트(프로젝트 설정에 맞춰)
EXPOSE 8080

# 4) 컨테이너 시작 명령
ENTRYPOINT ["java", "-jar", "/app.jar"]
